name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake doxygen clang-format
          sudo apt-get install -y libgtest-dev libtinyxml2-dev libcfitsio-dev libccfits-dev libplplot-dev libmysqlclient-dev libmysql++-dev libgsl-dev libtclap-dev
          sudo apt-get install plplot-driver-cairo
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          test ! -h /usr/local/lib/libgtest.a && sudo ln -s libgtest.a /usr/local/lib/libgtest.a
          test ! -h /usr/local/lib/libgtest_main.a && sudo ln -s libgtest_main.a /usr/local/lib/libgtest_main.a
          cd -
      - uses: actions/checkout@v2
      - name: Check code style
        run: |
          clang-format --dry-run -Werror *.h *.cpp include/*.h src/*.cpp
      - name: Make
        run: |
           make -f Makefile.server clean
           mkdir -p obj
           mkdir -p bin
           make -j -f Makefile.server
      - name: Unit tests
        run: |
          make -f Makefile.server tests
      - name: Build documentation
        run: |
          cd docs
          doxygen
