name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake doxygen clang-format
          sudo apt-get install -y libgtest-dev libtinyxml2-dev # libcfitsio libplplot-dev libmysqlclient-dev libmysql++-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo ln -s libgtest.a /usr/local/lib/libtest.a
          sudo ln -s libgtest_main.a /usr/local/lib/libgtest_main.a
          cd -
      - uses: actions/checkout@v2
      - name: Check code style
        run: |
          clang-format --dry-run -Werror *.h *.cpp include/*.h src/*.cpp
      - name: Unit tests
        run: |
          make tests
      - name: Build documentation
        run: |
          cd docs
          doxygen
